# Generated by Django 5.0.7 on 2024-08-20 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Athlete', '0002_alter_signup_mail_alter_signup_numbers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='numbers',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='username',
        ),
    ]
