# Generated by Django 5.0.7 on 2024-08-21 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Athlete', '0003_remove_signup_mail_remove_signup_numbers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
