# Generated by Django 5.0.7 on 2024-08-25 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Athlete', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
