# Generated by Django 5.0.7 on 2024-08-25 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Athlete', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoachView',
        ),
    ]
