# Generated by Django 5.0.7 on 2024-09-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Athlete', '0010_athleteinput_delete_athletelogin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AthleteInput',
            new_name='HealthInput',
        ),
    ]
