# Generated by Django 5.0.7 on 2024-09-08 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Athlete', '0012_healthinputs_delete_healthinput'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthInputs',
        ),
    ]
