# Generated by Django 5.0.7 on 2024-09-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Athlete', '0013_delete_healthinputs'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heartrate', models.CharField(max_length=255)),
                ('blood_pressure', models.CharField(max_length=255)),
                ('Temperature', models.CharField(max_length=255)),
            ],
        ),
    ]
