# Generated by Django 5.0.7 on 2024-09-13 07:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Athlete', '0014_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinputs',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
