# Generated by Django 5.0.7 on 2024-08-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoachSignup',
        ),
    ]
