# Generated by Django 5.0.7 on 2024-08-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachlogin',
            old_name='user',
            new_name='coach',
        ),
    ]
